/* Allegro data file object indexes, produced by grabber.exe */
/* Do not hand edit! */

#define BAR                 0       /* (bmp)  */
#define BAR2                1       /* (bmp)  */
#define BLOCK               2       /* (bmp)  */
#define BLOCK_RED           3       /* (bmp)  */
#define CURSOR              4       /* (bmp)  */
#define DELETE_SOUND        5       /* (spl)  */
#define EMPTY               6       /* (bmp)  */
#define GAME_FONT           7       /* (font) */
#define GAME_OVER           8       /* (bmp)  */
#define GAME_PALLETE        9       /* (pal)  */
#define MOVE_SOUND          10      /* (spl)  */
#define MUSIC01             11      /* (midi) */
#define MUSIC02             12      /* (midi) */
#define MUSIC03             13      /* (midi) */
#define PATTERN             14      /* (bmp)  */
#define TECH_FONT           15      /* (font) */
#define TETRIS              16      /* (bmp)  */
#define TITLE               17      /* (bmp)  */
#define WALL01              18      /* (bmp)  */
#define WALL02              19      /* (bmp)  */
#define WALL03              20      /* (bmp)  */
#define WALL04              21      /* (bmp)  */
#define WALL05              22      /* (bmp)  */
#define WALL06              23      /* (bmp)  */
